import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import useGetData from "./api/useGetData";
import FacetedSearch from "@/views/FacetedSearch/FacetedSearch";
import { Router, useRouter } from "next/router";
import { useKeyPress } from "@/hooks/useKeyPress";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { query, push } = useRouter();
  const { search, select } = query;
  const pressEnter = useKeyPress(13);
  const [searchInput, setSearchInput] = useState("");
  const filter = select?.toString().split("-");
  const { data, isLoading, isError } = useGetData(search?.toString(), filter); //TODO think about better option search?.toString()
  useEffect(() => {
    setSearchInput(search ? search.toString() : "");
  }, [search]);
  useEffect(() => {
    // TODO remove param when input is empty and user push enter
    if (pressEnter) {
      push({
        pathname: "/",
        query: { ...query, search: encodeURI(searchInput) },
      });
    }
  }, [pressEnter]);
  const searchBoxOnChange = (e: any) => {
    e.preventDefault();
    setSearchInput(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <input value={searchInput} onChange={searchBoxOnChange} />
        </div>
        <FacetedSearch />
        {isLoading && <div>is loading ...</div>}
        {isError && <div>Error!</div>}
        <div>
          <ul>
            {data?.map((item: any) => (
              <li className={styles.item} key={item.id}>
                {item?.title}
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}
